### ISSUE TITLE
[Tiled] TiledMap displaying wrong tiles

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#307]
There was a post [on the forums](http://community.monogame.net/t/tiledmap-displaying-wrong-tiles/8387) a couple of days ago. Moved it here to capture the problem. Anyone want to look into it?

> My tiled map looks as it is supposed to in Tiled Editor, but when I try to render it, it renders wrong textures for the tiles.
The map with the sprite sheets: dropbox6

> I'm using the latest version of MonoGame.Extended, which I compiled from the source.

> The problem seems to only affect tiles which are using textures from the second sprite sheet(the indoor one).

[house.zip](https://github.com/craftworkgames/MonoGame.Extended/files/593515/house.zip)

**Comment by OptimusPi** [comment]
I will look into this. I originally added support for multiple tilesets. So it's familiar with me.

**Comment by OptimusPi** [comment]
It's a bug. https://i.imgur.com/EUVBvHG.png
Sorry about that. I must have not fixed it properly. I don't know why it's broken but I'll find out and take care of it.

**Comment by craftworkgames** [comment]
It would be really good if we could include the attached "house" map as one of the demo's. That way we have a way to test this feature in the future.

**Comment by OptimusPi** [comment]
Yes it would. Is the art okay to include, no legal issues with that? I'm guessing it might be open game art, though. I don't know why I fixed this bug for my map but it doesn't work for this one. Yet to look into it.

When I fix it, may I make a pull request to a Demo project? Thanks.

**Comment by craftworkgames** [comment]
> Is the art okay to include, no legal issues with that?

The art looks like one of [Kenney's packs](http://kenney.nl/assets/roguelike-rpg-pack) so I think the license is very permissive. 

> License: (CC0 1.0 Universal) You're free to use these game assets in any project, personal or commercial. There's no need to ask permission before using these. Giving attribution is not required, but is greatly appreciated!

> When I fix it, may I make a pull request to a Demo project? Thanks.

Yes, absolutely. It's very important to keep the demos updated. That's currently the best way we have to make sure we haven't broken anything. Any improvements to the demos are quite welcome.

**Comment by jeffol** [comment]
I noticed when placing tiles beyond the first row of the tileset, there appears to be a calculation issue of what tile to render. It looks like an off-by-one error, per row of tiles. I made a test tileset to visualize the offset error (attached photo)

![tilesoff](https://cloud.githubusercontent.com/assets/3392831/20865327/51323530-b9d4-11e6-9086-998d35409bdf.png)

Just updated to the latest beta version to see if the issue I am having would be resolved. After getting up to date to 0.6.247-beta, the issue is not resolved. 

My tileset image size size is 296x296. It was also occurring with my actual tileset of 297x400 with 1 pixel borders.
![broken](https://cloud.githubusercontent.com/assets/3392831/20865365/37faf588-b9d5-11e6-8947-1d06fe7c5441.png)

**Comment by craftworkgames** [comment]
@jeffol I'm surprised we haven't noticed something so obvious. There must be something different about your TMX file compared to the ones in the demos.

Could you please attach your TMX and tileset (the test tileset you made to visualize the error would be great)?

**Comment by jeffol** [comment]
For sure. I was able to resolve my issue today by resizing my tileset, but obviously the issue still exists. I've attached the test files. Sorry I didn't attach them right away, it was a bit late when I posted.

[testmap.zip](https://github.com/craftworkgames/MonoGame.Extended/files/629934/testmap.zip)

**Comment by craftworkgames** [comment]
@jeffol Thanks mate.

    <tileset firstgid="1" name="tiles02" tilewidth="16" tileheight="16" tilecount="324" columns="18">
        <image source="tiles02.png" width="297" height="297"/>
    </tileset>

So as you said, the problem probably has something to do with the fact that the width and / or height of the tileset image is not divisible by 16 (the tile size).

I haven't had a change to properly look into it yet but I was able to easily reproduce the issue. Cheers.

**Comment by rafaelalmeidatk** [comment]
Maybe it's related? #122

**Comment by OptimusPi** [comment]
One strange clue, if I increase the tileset image a bit, until it's divisible by 16 (width and height),
Tiled Map Editor notices this and says "Would you like to increase the tile columns by 1?" 
So I clicked "No" to see what it would look like. And it looks the same as the bug.

 https://i.imgur.com/Js06O1y.png

I am going to look and make sure if Spacing attribute is read and applied correctly, and see if I can find a fix. Will let you know if I do.

**Comment by LithiumToast** [comment]
Found the problem.

https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Tiled/TiledTileSet.cs#L40

The test map provided earlier in this issue comments has a width of 296 which does not divide evenly by 16.

**Comment by craftworkgames** [comment]
Thanks mate. Looking forward to it :)

**Comment by LithiumToast** [comment]
@craftworkgames This can also be closed.

**Comment by craftworkgames** [comment]
@LithiumToast If you spot any issues that can be closed just close them and leave a comment about why it was closed. We can always reopen them.

**Comment by LithiumToast** [comment]
I don't have the permissions.

**Comment by craftworkgames** [comment]
> I don't have the permissions.

Ah right. That makes sense.

I'd seen other people close issues before so I just assumed. Now that I think about it I guess you have permission to close issues that you open.

Looking into it a little further it appears you can only have those fine grained user permissions on Organization accounts.
